# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT
---
- name: Packit-service validation deployment
  hosts: all
  vars:
    # path with needed secrets (github, sentry, copr)
    path_to_secrets: ""
    project: packit-service-validation
    host: https://open.paas.redhat.com
    # oc login <the above host value>, oc whoami -t
    # OR via Openshift web GUI: click on your login in top right corner, 'Copy Login Command', take the part after --token=
    api_key: ""
    validate_certs: false

  tasks:
    - name: Deploy secrets
      # https://docs.ansible.com/k8s_module.html
      k8s:
        namespace: "{{ project }}"
        definition: "{{ item }}"
        host: "{{ host }}"
        api_key: "{{ api_key }}"
        validate_certs: "{{ validate_certs }}"
      loop:
        - "{{ lookup('template', './openshift/secret-config.yml.j2') }}"
        - "{{ lookup('template', './openshift/secret-sentry.yml.j2') }}"
        - "{{ lookup('template', './openshift/secret-github.yml.j2') }}"
      tags:
        - always

    - name: Deploy cron job for running validation script
      k8s:
        namespace: "{{ project }}"
        definition: "{{ lookup('template', './openshift/job-run-validation.yaml')  }}"
        host: "{{ host }}"
        api_key: "{{ api_key }}"
        validate_certs: "{{ validate_certs }}"
