apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: run-validation
spec:
  schedule: "0 4 * * *"
  backoffLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: run-validation
              image: usercont/packit-service-validation
              env:
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: github-token
                      key: token
                - name: SENTRY_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: packit-sentry
                      key: sentry
              command: ["python3", "/usr/bin/packit-service-validation.py"]
              volumeMounts:
                - name: config
                  mountPath: ~/.config/
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "100m"
                limits:
                  memory: "128Mi"
                  cpu: "100m"
          restartPolicy: OnFailure
