# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Check that the deployment resources are up to date
  when: zuul is not defined and check_up_to_date
  block:
    - name: Get HEAD from the remote
      ansible.builtin.command:
        chdir: "{{ project_dir }}"
        cmd: "git ls-remote {{ deployment_repo_url }} main"
      register: remote_head
      changed_when: remote_head.rc != 0
      failed_when: remote_head.rc != 0
    - name: Get local HEAD
      ansible.builtin.command:
        chdir: "{{ project_dir }}"
        cmd: git show-ref -s refs/heads/main
      register: local_head
      changed_when: local_head.rc != 0
      failed_when: local_head.rc != 0
    - name: Compare deployment repo hashes
      ansible.builtin.assert:
        that:
          - remote_head.stdout.split()[0] == local_head.stdout
        fail_msg: "The main branch of the deployment repo is not up to date"
    - name: Check HEAD from secrets remote
      ansible.builtin.command:
        chdir: "{{ path_to_secrets }}"
        cmd: "git ls-remote {{ secrets_repo_url }} master"
      register: remote_secrets_head
      changed_when: remote_secrets_head.rc != 0
      failed_when: remote_secrets_head.rc != 0
    - name: Check HEAD from local secrets
      ansible.builtin.command:
        chdir: "{{ path_to_secrets }}"
        cmd: git show-ref -s refs/heads/master
      register: local_secrets_head
      changed_when: local_secrets_head.rc != 0
      failed_when: local_secrets_head.rc != 0
    - name: Compare secrets repo hashes
      ansible.builtin.assert:
        that:
          - remote_secrets_head.stdout.split()[0] == local_secrets_head.stdout
        fail_msg: "The master branch of the secrets repo is not up to date"
    - name: Calculate the diff of the current vars file
      when: check_vars_template_diff
      ansible.builtin.shell:
        chdir: "{{ project_dir }}"
        # Remove the keys expected to be different and lines specific to the diff-format.
        cmd: >-
          diff vars/{{ service }}/{{ deployment }}.yml vars/{{ service }}/{{ deployment }}_template.yml |
          sed '/api_key/d;/secrets_repo_url/d;/[0-9]\+c[0-9]\+/d;/---/d'
      register: diff
      changed_when: diff.rc != 0
      failed_when: diff.rc != 0
    - name: Check that there are no unexpected lines in the diff
      when: check_vars_template_diff
      ansible.builtin.assert:
        that:
          - not diff.stdout
        fail_msg: >-
          The diff between
          'vars/{{ service }}/{{ deployment }}.yml' and
          'vars/{{ service }}/{{ deployment }}_template.yml' is has some
          unexpected lines: {{ diff.stdout }}
