# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Set mandatory_deploymentconfigs fact
  set_fact:
    mandatory_deploymentconfigs:
      - postgres-13
      - redis
      - packit-service
  tags:
    - always
- name: Set optional_deploymentconfigs fact
  set_fact:
    optional_deploymentconfigs:
      tokman: "{{ with_tokman }}"
      packit-service-fedmsg: "{{ with_fedmsg }}"
      packit-service-beat: "{{ with_beat }}"
      packit-dashboard: "{{ with_dashboard }}"
      pushgateway: "{{ with_pushgateway }}"
      nginx: "{{ with_pushgateway }}"
  tags:
    - always
- name: Set deploymentconfigs fact
  set_fact:
    # To know what DCs rollouts to wait for and also to check in tests
    deploymentconfigs: '{{ mandatory_deploymentconfigs + optional_deploymentconfigs|dict2items|selectattr("value", "equalto", true)|list|map(attribute="key")|flatten }}'
  tags:
    - always
