# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

# -------------------------------------------------------------------
# Variables needed by Ansible playbooks in playbooks/
# -------------------------------------------------------------------

# Openshift project/namespace name
project: packit-prod

# Openshift cluster url
host: https://console.pro-eu-west-1.openshift.com

# oc login <the above host value>, oc whoami -t
# OR via Openshift web GUI: click on your login in top right corner, 'Copy Login Command', take the part after --token=
api_key: ""

# validate_certs: true

# with_tokman: true

# if you want to deploy fedmsg, please make sure to
# edit the queue name in secrets/*/fedora.toml
# with_fedmsg: true

# with_centosmsg: true

# with_redis_commander: false

# with_flower: false

# with_beat: true

# with_dashboard: true

# with_pushgateway: true

# with_repository_cache: true
repository_cache_storage: 10Gi

# you can set the sandbox namespace name explicitly like this
# sandbox_namespace: packit-prod-sandbox

# image to use for service
# image: quay.io/packit/packit-service:{{ deployment }}

# image to use for worker
# image_worker: quay.io/packit/packit-worker:{{ deployment }}

# image to use for fedora messaging consumer
# image_fedmsg: quay.io/packit/packit-service-fedmsg:{{ deployment }}

# image to use for centos messaging consumer
# image_centosmsg: quay.io/packit/packit-service-centosmsg:{{ deployment }}

# image to use for dashboard
# image_dashboard: "quay.io/packit/dashboard:{{ deployment }}"

# image to use for tokman
# image_tokman: "quay.io/packit/tokman:{{ deployment }}"

# Path to secrets (in case you don't have it in the root of this project)
# path_to_secrets: ../secrets

# Used in dev/Zuul deployment to tag & push images to cluster.
# It's set to "/usr/bin/podman" if there's podman installed, or to 'docker' otherwise.
# If you still want to use docker even when podman is installed, set:
# container_engine: docker

# Celery retry parameters
# celery_retry_limit: 2
# celery_retry_backoff: 3

# Number of worker pods to be deployed to serve the queues
# workers_all_tasks: 1
workers_short_running: 1
workers_long_running: 1
# pushgateway_address: http://pushgateway
