apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: import-images
spec:
  # https://crontab.guru
  # STG: Once every hour (at minute 0)
  # schedule: "0 * * * *"
  # PROD: At 02:00 on Tuesday
  schedule: "0 2 * * 2"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: import-images
              image: quay.io/packit/import-images
              imagePullPolicy: IfNotPresent
              env:
                - name: KUBECONFIG
                  value: /tmp/.kube/config
                - name: HOST
                  # value: https://api.pro-eu-west-1.openshift.com
                  value: https://api.auto-prod.gi0n.p1.openshiftapps.com:6443
                # - name: SERVICE
                #   value: stream
                - name: DEPLOYMENT
                  value: stg
                # value: prod
                - name: TOKEN
                  valueFrom:
                    secretKeyRef:
                      # packit-prod @ auto
                      name: importimager-token-gjfb6
                      # stream-stg
                      # name: importimager-token-9mvsw
                      # stream-prod
                      # name: importimager-token-8cm2b
                      key: token
              resources:
                limits:
                  memory: "80Mi"
                  cpu: "100m"
          restartPolicy: OnFailure
