# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: flower
spec:
  selector:
    matchLabels:
      component: flower
  template:
    metadata:
      labels:
        component: flower
    spec:
      containers:
        - name: flower
          image: mher/flower
          env:
            - name: CELERY_BROKER_URL
              value: redis://redis:6379/0
            - name: FLOWER_PORT
              value: "5555"
          ports:
            - containerPort: 5555
          resources:
            requests:
              memory: "80Mi"
              cpu: "20m"
            limits:
              memory: "80Mi"
              cpu: "20m"
  replicas: 1
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: flower
spec:
  ports:
    - name: "5555"
      port: 5555
      targetPort: 5555
  selector:
    component: flower
