# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Check a deployment
  hosts: all
  vars:
    service: "{{ lookup('env', 'SERVICE') | default('packit', True) }}"
    deployment: "{{ lookup('env', 'DEPLOYMENT') }}"
  tasks:
    - include_tasks: tasks/project-dir.yml

    - name: include variables
      include_vars: "{{ project_dir }}/vars/{{ service }}/{{ deployment }}.yml"

    - name: Getting DCs
      include_tasks: tasks/set-facts.yml

    - name: Checking running pods of {{ DCs }}
      include_tasks: tasks/check-pod-running.yml
      loop: "{{ DCs + ['packit-worker'] }}"
