# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

- name: Rebuild base image
  hosts: all
  vars:
    project: "packit-infra"
    project_dir: "{{ playbook_dir }}/.."
    path_to_secrets: "{{ project_dir }}/secrets"
    validate_certs: no

  tasks:
    - name: include variables
      include_vars: ../vars/infra.yml

    - name: oc login
      command: oc login {{ host }} --token={{ api_key }} --insecure-skip-tls-verify
      # it doesn't change anything, so don't report 'changed'
      changed_when: false

    - name: oc change project
      command: oc project {{ project }}

    - name: infra secrets
      include_vars: "{{ path_to_secrets }}/infra/secrets.yaml"
      tags:
        - always

    - name: Deploy infra secrets
      k8s:
        namespace: "{{ project }}"
        definition: "{{ item }}"
        host: "{{ host }}"
        api_key: "{{ api_key }}"
        validate_certs: "{{ validate_certs }}"
      loop:
        - "{{ lookup('template', '{{ project_dir }}/openshift/secret-rebuild-base-image.yml.j2') }}"
      tags:
        - always

    - name: deploy rebuild-base-image cronjob
      command: oc apply -f ../cron-jobs/rebuild-base-image/rebuild-base-image.yaml
