# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Check deployment
  hosts: all
  tasks:
    - name: Run 'make check'
      ansible.builtin.command: make check
      environment:
        DEPLOYMENT: dev
        ANSIBLE_STDOUT_CALLBACK: debug
      args:
        chdir: "{{ zuul.project.src_dir }}"
      become: true
      changed_when: false
