# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Check deployment
  hosts: all
  tasks:
    - command: make check
      environment:
        DEPLOYMENT: dev
        ANSIBLE_STDOUT_CALLBACK: debug
      args:
        chdir: "{{ project_dir }}"
      become: true
