- name: Encrypt secrets for zuul
  hosts: localhost
  vars:
    deployment: "{{ lookup('env', 'DEPLOYMENT') }}"
  tasks:
  - name: Download the zuul
    git:
        repo: 'https://opendev.org/zuul/zuul.git'
        dest: /tmp/zuul
        clone: yes
  - name: Creates zuul secrets directory
    file:
      path: ../secrets/zuul
      state: directory
  - name: Encrypt {{ deployment }} secrets to be used inside Zuul CI
    command: /tmp/zuul/tools/encrypt_secret.py --insecure --tenant local --infile ../secrets/{{ deployment }}/{{ item }} --outfile ../secrets/zuul/{{ item }}-secret.yaml https://softwarefactory-project.io/zuul/ packit-service/packit-service
    with_items:
    - cert.pem
    - chain.pem
    - copr
    - fullchain.pem
    - httpd-packit.conf
    - id_rsa
    - id_rsa.pub
    - packit-service.yaml
    - private-key.pem
    - privkey.pem
    - ssh_config

  - name: Encrypt fedora keytab using base64 first
    block:
    - shell: "cat ../secrets/{{ deployment }}/fedora.keytab | base64 > /tmp/fedora.keytab.b64"
    - command: /tmp/zuul/tools/encrypt_secret.py --insecure --tenant local --infile /tmp/fedora.keytab.b64 --outfile ../secrets/zuul/fedora.keytab-secret.yaml https://softwarefactory-project.io/zuul/ packit-service/packit-service

  - name: Fill the <name> in newly generated secrets
    replace:
      path: ../secrets/zuul/{{ item }}-secret.yaml
      regexp: '<name>'
      replace: "{{ item }}"
    with_items:
    - cert.pem
    - chain.pem
    - copr
    - fullchain.pem
    - httpd-packit.conf
    - id_rsa
    - id_rsa.pub
    - packit-service.yaml
    - private-key.pem
    - privkey.pem
    - ssh_config
    - fedora.keytab

  - name: Fill the <fieldname> in newly generated secrets
    replace:
      path: ../secrets/zuul/{{ item }}-secret.yaml
      regexp: '<fieldname>'
      replace: 'value'
    with_items:
    - cert.pem
    - chain.pem
    - copr
    - fullchain.pem
    - httpd-packit.conf
    - id_rsa
    - id_rsa.pub
    - packit-service.yaml
    - private-key.pem
    - privkey.pem
    - ssh_config
    - fedora.keytab
