# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Generate config files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ path_to_secrets }}/{{ item }}"
    mode: 0644
  loop:
    - packit-service.yaml.j2
    - extra-vars.yml
    - fedora.toml.j2
    - copr
    - ssh_config
