name: Build & push cron-job images
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - cron-jobs/import-images/**
      - cron-jobs/packit-service-validation/**

jobs:
  build-and-push:
    # To not run in forks
    if: github.repository_owner == 'packit'

    name: Build and push image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: import-images
          - image: packit-service-validation

    env:
      path: cron-jobs/${{ matrix.image }}/

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Add short SHA to the list of tags
        shell: bash
        run: |
          echo "::set-output name=tags::latest ${GITHUB_SHA::7}"
        id: calculate-tags

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: ${{ env.path }}Containerfile
          image: ${{ matrix.image }}
          context: ${{ env.path }}
          oci: true
          tags: ${{ steps.calculate-tags.outputs.tags }}

      - name: Push To Quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/packit
          username: ${{ secrets.QUAY_IMAGE_BUILDER_USERNAME }}
          password: ${{ secrets.QUAY_IMAGE_BUILDER_TOKEN }}
